# Generated by Django 4.2.6 on 2023-11-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoimgApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Subtitle', models.CharField(blank=True, max_length=254, null=True)),
                ('ImagePic', models.ImageField(blank=True, null=True, upload_to='AboutDBFolder')),
                ('imageWidth', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('imageHeight', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
