# Generated by Django 4.2.6 on 2023-11-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoimgApp', '0002_aboutdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDB',
            fields=[
                ('slID', models.AutoField(primary_key=True, serialize=False)),
                ('selectFile', models.FileField(blank=True, null=True, upload_to='FileDBFolder')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutDB',
        ),
    ]
